server:
  port: 8080
spring:
  security:
    user:
      name: user
      password: user123
#    oauth2:
#      client:
#        registration:
#          client1:
#            client-id: client
#            client-secret: client123
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework.security: WARN